// GENERATED by tools/gencaps.chuks from core/capabilities.json. Do not edit.
//
// The Android half of ios/ChuksCaps.gen.swift, from the same declaration.
package com.chuks.app

/** bg.once: run once, no sooner than N seconds */
data class BgOnceArgs(val name: String, val seconds: Int, val constraints: String)

/** bg.periodic: repeat no sooner than N seconds */
data class BgPeriodicArgs(val name: String, val seconds: Int, val constraints: String)

/** bg.processing: long work wanting power and network */
data class BgProcessingArgs(val name: String, val seconds: Int, val constraints: String)

/** bg.result: a background handler finished */
data class BgResultArgs(val name: String, val ok: Boolean)

/** ble.read: read a characteristic once */
data class BleReadArgs(val deviceId: String, val service: String, val characteristic: String)

/** ble.subscribe: stream a characteristic's values */
data class BleSubscribeArgs(val deviceId: String, val service: String, val characteristic: String)

/** ble.write: write a characteristic */
data class BleWriteArgs(val deviceId: String, val service: String, val characteristic: String, val valueHex: String)

/** brightness.keepAwake: hold the screen awake */
data class BrightnessKeepAwakeArgs(val on: Boolean)

/** brightness.set: screen brightness, 0 to 1 */
data class BrightnessSetArgs(val level: Double)

/** calendar.create: create an event */
data class CalendarCreateArgs(val title: String, val startInMin: Int, val durationMin: Int)

/** calendar.upcoming: events in the next N days */
data class CalendarUpcomingArgs(val days: Int)

/** fs.write: write a file in the app's directory */
data class FsWriteArgs(val name: String, val content: String)

/** haptics.vibrate: a single buzz, in milliseconds */
data class HapticsVibrateArgs(val ms: Int)

/** location.watchBackground: the Android tracking notification */
data class LocationWatchBackgroundArgs(val title: String, val body: String)

/** notif.notify: post a local notification */
data class NotifNotifyArgs(val title: String, val body: String)

/** pedometer.query: step history over a past window */
data class PedometerQueryArgs(val secondsAgo: Int)

/** secure.set: store a secret in the OS keystore */
data class SecureSetArgs(val key: String, val value: String)

/** torch.set: flashlight on or off */
data class TorchSetArgs(val on: Boolean)

object ChuksCaps {
    fun bgOnce(f: List<String>, token: String, host: ChuksArgFailer): BgOnceArgs? {
        if (f.size < 3) { host.argMissing(token, "bg.once", 3, f.size); return null }
        val name = f[0]
        val seconds = f[1].toIntOrNull() ?: run { host.argBad(token, "bg.once", "seconds", "int", f[1]); return null }
        val constraints = f[2]
        return BgOnceArgs(name, seconds, constraints)
    }

    fun bgPeriodic(f: List<String>, token: String, host: ChuksArgFailer): BgPeriodicArgs? {
        if (f.size < 3) { host.argMissing(token, "bg.periodic", 3, f.size); return null }
        val name = f[0]
        val seconds = f[1].toIntOrNull() ?: run { host.argBad(token, "bg.periodic", "seconds", "int", f[1]); return null }
        val constraints = f[2]
        return BgPeriodicArgs(name, seconds, constraints)
    }

    fun bgProcessing(f: List<String>, token: String, host: ChuksArgFailer): BgProcessingArgs? {
        if (f.size < 3) { host.argMissing(token, "bg.processing", 3, f.size); return null }
        val name = f[0]
        val seconds = f[1].toIntOrNull() ?: run { host.argBad(token, "bg.processing", "seconds", "int", f[1]); return null }
        val constraints = f[2]
        return BgProcessingArgs(name, seconds, constraints)
    }

    fun bgResult(f: List<String>, token: String, host: ChuksArgFailer): BgResultArgs? {
        if (f.size < 2) { host.argMissing(token, "bg.result", 2, f.size); return null }
        val name = f[0]
        val ok = f[1] == "1"
        return BgResultArgs(name, ok)
    }

    fun bleRead(f: List<String>, token: String, host: ChuksArgFailer): BleReadArgs? {
        if (f.size < 3) { host.argMissing(token, "ble.read", 3, f.size); return null }
        val deviceId = f[0]
        val service = f[1]
        val characteristic = f[2]
        return BleReadArgs(deviceId, service, characteristic)
    }

    fun bleSubscribe(f: List<String>, token: String, host: ChuksArgFailer): BleSubscribeArgs? {
        if (f.size < 3) { host.argMissing(token, "ble.subscribe", 3, f.size); return null }
        val deviceId = f[0]
        val service = f[1]
        val characteristic = f[2]
        return BleSubscribeArgs(deviceId, service, characteristic)
    }

    fun bleWrite(f: List<String>, token: String, host: ChuksArgFailer): BleWriteArgs? {
        if (f.size < 4) { host.argMissing(token, "ble.write", 4, f.size); return null }
        val deviceId = f[0]
        val service = f[1]
        val characteristic = f[2]
        val valueHex = f[3]
        return BleWriteArgs(deviceId, service, characteristic, valueHex)
    }

    fun brightnessKeepAwake(f: List<String>, token: String, host: ChuksArgFailer): BrightnessKeepAwakeArgs? {
        if (f.size < 1) { host.argMissing(token, "brightness.keepAwake", 1, f.size); return null }
        val on = f[0] == "1"
        return BrightnessKeepAwakeArgs(on)
    }

    fun brightnessSet(f: List<String>, token: String, host: ChuksArgFailer): BrightnessSetArgs? {
        if (f.size < 1) { host.argMissing(token, "brightness.set", 1, f.size); return null }
        val level = f[0].toDoubleOrNull() ?: run { host.argBad(token, "brightness.set", "level", "number", f[0]); return null }
        return BrightnessSetArgs(level)
    }

    fun calendarCreate(f: List<String>, token: String, host: ChuksArgFailer): CalendarCreateArgs? {
        if (f.size < 3) { host.argMissing(token, "calendar.create", 3, f.size); return null }
        val title = f[0]
        val startInMin = f[1].toIntOrNull() ?: run { host.argBad(token, "calendar.create", "startInMin", "int", f[1]); return null }
        val durationMin = f[2].toIntOrNull() ?: run { host.argBad(token, "calendar.create", "durationMin", "int", f[2]); return null }
        return CalendarCreateArgs(title, startInMin, durationMin)
    }

    fun calendarUpcoming(f: List<String>, token: String, host: ChuksArgFailer): CalendarUpcomingArgs? {
        if (f.size < 1) { host.argMissing(token, "calendar.upcoming", 1, f.size); return null }
        val days = f[0].toIntOrNull() ?: run { host.argBad(token, "calendar.upcoming", "days", "int", f[0]); return null }
        return CalendarUpcomingArgs(days)
    }

    fun fsWrite(f: List<String>, token: String, host: ChuksArgFailer): FsWriteArgs? {
        if (f.size < 2) { host.argMissing(token, "fs.write", 2, f.size); return null }
        val name = f[0]
        val content = f[1]
        return FsWriteArgs(name, content)
    }

    fun hapticsVibrate(f: List<String>, token: String, host: ChuksArgFailer): HapticsVibrateArgs? {
        if (f.size < 1) { host.argMissing(token, "haptics.vibrate", 1, f.size); return null }
        val ms = f[0].toIntOrNull() ?: run { host.argBad(token, "haptics.vibrate", "ms", "int", f[0]); return null }
        return HapticsVibrateArgs(ms)
    }

    fun locationWatchBackground(f: List<String>, token: String, host: ChuksArgFailer): LocationWatchBackgroundArgs? {
        if (f.size < 2) { host.argMissing(token, "location.watchBackground", 2, f.size); return null }
        val title = f[0]
        val body = f[1]
        return LocationWatchBackgroundArgs(title, body)
    }

    fun notifNotify(f: List<String>, token: String, host: ChuksArgFailer): NotifNotifyArgs? {
        if (f.size < 2) { host.argMissing(token, "notif.notify", 2, f.size); return null }
        val title = f[0]
        val body = f[1]
        return NotifNotifyArgs(title, body)
    }

    fun pedometerQuery(f: List<String>, token: String, host: ChuksArgFailer): PedometerQueryArgs? {
        if (f.size < 1) { host.argMissing(token, "pedometer.query", 1, f.size); return null }
        val secondsAgo = f[0].toIntOrNull() ?: run { host.argBad(token, "pedometer.query", "secondsAgo", "int", f[0]); return null }
        return PedometerQueryArgs(secondsAgo)
    }

    fun secureSet(f: List<String>, token: String, host: ChuksArgFailer): SecureSetArgs? {
        if (f.size < 2) { host.argMissing(token, "secure.set", 2, f.size); return null }
        val key = f[0]
        val value = f[1]
        return SecureSetArgs(key, value)
    }

    fun torchSet(f: List<String>, token: String, host: ChuksArgFailer): TorchSetArgs? {
        if (f.size < 1) { host.argMissing(token, "torch.set", 1, f.size); return null }
        val on = f[0] == "1"
        return TorchSetArgs(on)
    }

}
