#!/usr/bin/env bash
# Autolinking for Android, shared by every build path.
#
# A package declares its Kotlin in its own chuks.json (see appconfig.chuks); the sources
# compile in beside the host, and a generated registry routes the commands whose namespace
# they claim. The iOS half of this lives in ios/native-packages.sh; the two must stay in
# step, since a package ships both.
#
# In its own file because the DEV path needs it too. It used to sit inline in build.sh, so
# `chuks dev:android` compiled two Kotlin files and nothing else, and an app with a native
# package could not use hot reload at all.
#
# It also owns the answer to "what Kotlin compiles into this app", which is the same
# question: the host's own files and the installed packages' files are one source list,
# and both build paths need the identical one.
#
# Callers must have SDKROOT, PROJDIR, PKGDIR, AJAR and OUT set. Sets PKG_KT, KT_SRC and
# KT_CP, and writes $OUT/ChuksPackageModules.kt and $OUT/ChuksBuild.kt.

chuks_android_native_packages() {
PKG_KT="$(chuks run "$SDKROOT/appconfig.chuks" "$PROJDIR" mobile-sources android 2>/dev/null | tr '\n' ' ')"
{
    echo "// GENERATED by android/build.sh. Every installed package that ships a native"
    echo "// capability for Android, so the registry can route commands to it."
    echo "package com.chuks.app"
    echo "object ChuksPackageModules {"
    echo "    fun factories(): Map<String, (ChuksModuleHost) -> ChuksNativeModule> = mapOf("
    chuks run "$SDKROOT/appconfig.chuks" "$PROJDIR" mobile-modules android 2>/dev/null |
        while IFS="$(printf '\t')" read -r ns cls; do
            [ -n "$cls" ] && echo "        \"$ns\" to { h: ChuksModuleHost -> $cls(h) },"
        done
    echo "    )"
    echo "    // The view kinds those packages supply, if any."
    echo "    fun views(): Map<String, (ChuksViewHost) -> ChuksNativeView> = mapOf("
    chuks run "$SDKROOT/appconfig.chuks" "$PROJDIR" mobile-views android 2>/dev/null |
        while IFS="$(printf '\t')" read -r kind cls; do
            [ -n "$cls" ] && echo "        \"$kind\" to { h: ChuksViewHost -> $cls(h) },"
        done
    echo "    )"
    echo "}"
} > "$OUT/ChuksPackageModules.kt"
    [ -n "$PKG_KT" ] && echo "   native packages: $(echo $PKG_KT | wc -w | tr -d ' ') source file(s)"
    return 0
}

# A capability is one thing with two implementations, so the build says when the two
# disagree. Covers the framework's own hosts as well as every installed package. An undeclared gap is loud: it means a capability that is shipped and
# documented but dead on one platform, whose only other symptom is a callback that
# never fires. A difference the package DECLARED is counted, not listed.
chuks_capability_check() {
    local sym gaps notes
    sym="$(chuks run "$SDKROOT/appconfig.chuks" "$PROJDIR" mobile-symmetry "$SDKROOT" 2>/dev/null)"
    [ -n "$sym" ] || return 0
    gaps="$(printf '%s\n' "$sym" | grep -c '^gap' || true)"
    notes="$(printf '%s\n' "$sym" | grep -c '^note' || true)"
    if [ "$gaps" -gt 0 ]; then
        echo "   capability check: $gaps problem(s)"
        printf '%s\n' "$sym" | awk -F'\t' '$1=="gap" { printf "      %s  %s\n", $3, $4 }'
        echo "      Nothing answers a name like these, and nothing will say so at runtime: a command"
        echo "      reaches no capability, a view kind renders an empty container. Implement it, fix"
        echo "      the spelling, or declare the difference: \"capabilities\" and \"views\" in a package's"
        echo "      chuks.json, \"coreCapabilities\" in the SDK's."
    fi
    [ "$notes" -gt 0 ] && echo "   capability check: $notes declared platform difference(s)"
    return 0
}

# Every Kotlin file that compiles into the app, host and packages alike, plus the
# classpath they need. build-cmr.sh used to name two of these by hand and so was missing
# ChuksBuild, ChuksModule, the services and the package registry: it could not build ANY
# app, with or without a native package.
#
# `AJ` (app.json reader) must be defined by the caller, as both build scripts do.
chuks_android_kotlin_sources() {
    local restore_window
    restore_window="$(AJ state-restore-window)"; [ -n "$restore_window" ] || restore_window=1800
    # Build-time constants from app.json. Generated rather than read at runtime because
    # the host needs them before anything is mounted.
    cat > "$OUT/ChuksBuild.kt" <<KTB
// GENERATED by android/native-packages.sh from the project's app.json.
package com.chuks.app
object ChuksBuild {
    const val STATE_RESTORE_WINDOW = $restore_window
}
KTB
    KT_SRC="$OUT/ChuksBuild.kt $PKGDIR/MainActivity.kt $PKGDIR/ChuksEffects.kt $PKGDIR/ChuksModule.kt $PKGDIR/ChuksJobService.kt $PKGDIR/ChuksLocationService.kt $OUT/ChuksPackageModules.kt $PKG_KT"
    KT_CP="$AJAR"
    return 0
}
