/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package chuks/cmd/cmr */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 10 "cabi_compat.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 15 "cmr.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void chuks_cmr_set_tmpdir(char* path);
extern int32_t chuks_cmr_boot(char* bundle, int32_t length);
extern int32_t chuks_cmr_apply_delta(char* delta, int32_t length);
extern void chuks_init(void);
extern int chuks_mount(void);
extern int chuks_remount(void);
extern int chuks_tick(void);
extern int chuks_dispatch(char* action);
extern int chuks_dispatchInput(char* action, char* value);
extern int chuks_setViewport(int top, int height, int width);
extern char* chuks_drain(void);
extern void chuks_free_str(char* p);
extern char* chuks_cmr_save_state(void);
extern void chuks_cmr_load_state(char* state);
extern void chuks_set_count(int n);
extern void chuks_setColorScheme(int dark);
extern int chuks_colorSchemeFollows(void);
extern void chuks_setInsets(int top, int right, int bottom, int left);
extern void chuks_setPlatform(char* os, char* version, char* model, int isTablet);
extern int chuks_resolve(char* token, char* payload);
extern int chuks_cancelToken(char* token);
extern int chuks_fail(char* token, char* message);
extern char* chuks_saveState(void);
extern void chuks_loadState(char* data);
extern void chuks_set_wake(void* cb);
extern char* cmr_version(void);
extern uint64_t cmr_create(void);
extern void cmr_destroy(uint64_t h);
extern char* cmr_last_error(uint64_t h);
extern void cmr_free(uint64_t _, char* ptr);
extern int32_t cmr_load(uint64_t h, char* bundle, int32_t length);
extern int32_t cmr_reload(uint64_t h, char* bundle, int32_t length);
extern int32_t cmr_mount(uint64_t h, char** outPtr, int32_t* outLen);
extern int32_t cmr_tick(uint64_t h, char** outPtr, int32_t* outLen);
extern int32_t cmr_dispatch(uint64_t h, char* event, int32_t elen, char** outPtr, int32_t* outLen);
extern int32_t cmr_viewport(uint64_t h, int32_t top, int32_t height, char** outPtr, int32_t* outLen);

#ifdef __cplusplus
}
#endif
