// GENERATED by tools/gencaps.chuks from core/capabilities.json. Do not edit.
//
// One decoder per capability. Each answers a value whose fields are named and
// typed, or fails the token with a message naming the argument that was wrong,
// which is the difference between a capability that reports a problem and one
// that quietly acts on a zero.
import Foundation

enum ChuksCaps {
    /// bg.once: run once, no sooner than N seconds
    struct BgOnceArgs {
        let name: String
        let seconds: Int
        let constraints: String
    }
    static func bgOnce(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BgOnceArgs? {
        guard f.count >= 3 else {
            host.argMissing(token, "bg.once", 3, f.count); return nil
        }
        let name = f[0]
        guard let seconds = Int(f[1]) else { host.argBad(token, "bg.once", "seconds", "int", f[1]); return nil }
        let constraints = f[2]
        return BgOnceArgs(name: name, seconds: seconds, constraints: constraints)
    }

    /// bg.periodic: repeat no sooner than N seconds
    struct BgPeriodicArgs {
        let name: String
        let seconds: Int
        let constraints: String
    }
    static func bgPeriodic(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BgPeriodicArgs? {
        guard f.count >= 3 else {
            host.argMissing(token, "bg.periodic", 3, f.count); return nil
        }
        let name = f[0]
        guard let seconds = Int(f[1]) else { host.argBad(token, "bg.periodic", "seconds", "int", f[1]); return nil }
        let constraints = f[2]
        return BgPeriodicArgs(name: name, seconds: seconds, constraints: constraints)
    }

    /// bg.processing: long work wanting power and network
    struct BgProcessingArgs {
        let name: String
        let seconds: Int
        let constraints: String
    }
    static func bgProcessing(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BgProcessingArgs? {
        guard f.count >= 3 else {
            host.argMissing(token, "bg.processing", 3, f.count); return nil
        }
        let name = f[0]
        guard let seconds = Int(f[1]) else { host.argBad(token, "bg.processing", "seconds", "int", f[1]); return nil }
        let constraints = f[2]
        return BgProcessingArgs(name: name, seconds: seconds, constraints: constraints)
    }

    /// bg.result: a background handler finished
    struct BgResultArgs {
        let name: String
        let ok: Bool
    }
    static func bgResult(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BgResultArgs? {
        guard f.count >= 2 else {
            host.argMissing(token, "bg.result", 2, f.count); return nil
        }
        let name = f[0]
        let ok = (f[1] == "1")
        return BgResultArgs(name: name, ok: ok)
    }

    /// ble.read: read a characteristic once
    struct BleReadArgs {
        let deviceId: String
        let service: String
        let characteristic: String
    }
    static func bleRead(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BleReadArgs? {
        guard f.count >= 3 else {
            host.argMissing(token, "ble.read", 3, f.count); return nil
        }
        let deviceId = f[0]
        let service = f[1]
        let characteristic = f[2]
        return BleReadArgs(deviceId: deviceId, service: service, characteristic: characteristic)
    }

    /// ble.subscribe: stream a characteristic's values
    struct BleSubscribeArgs {
        let deviceId: String
        let service: String
        let characteristic: String
    }
    static func bleSubscribe(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BleSubscribeArgs? {
        guard f.count >= 3 else {
            host.argMissing(token, "ble.subscribe", 3, f.count); return nil
        }
        let deviceId = f[0]
        let service = f[1]
        let characteristic = f[2]
        return BleSubscribeArgs(deviceId: deviceId, service: service, characteristic: characteristic)
    }

    /// ble.write: write a characteristic
    struct BleWriteArgs {
        let deviceId: String
        let service: String
        let characteristic: String
        let valueHex: String
    }
    static func bleWrite(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BleWriteArgs? {
        guard f.count >= 4 else {
            host.argMissing(token, "ble.write", 4, f.count); return nil
        }
        let deviceId = f[0]
        let service = f[1]
        let characteristic = f[2]
        let valueHex = f[3]
        return BleWriteArgs(deviceId: deviceId, service: service, characteristic: characteristic, valueHex: valueHex)
    }

    /// brightness.keepAwake: hold the screen awake
    struct BrightnessKeepAwakeArgs {
        let on: Bool
    }
    static func brightnessKeepAwake(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BrightnessKeepAwakeArgs? {
        guard f.count >= 1 else {
            host.argMissing(token, "brightness.keepAwake", 1, f.count); return nil
        }
        let on = (f[0] == "1")
        return BrightnessKeepAwakeArgs(on: on)
    }

    /// brightness.set: screen brightness, 0 to 1
    struct BrightnessSetArgs {
        let level: Double
    }
    static func brightnessSet(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> BrightnessSetArgs? {
        guard f.count >= 1 else {
            host.argMissing(token, "brightness.set", 1, f.count); return nil
        }
        guard let level = Double(f[0]) else { host.argBad(token, "brightness.set", "level", "number", f[0]); return nil }
        return BrightnessSetArgs(level: level)
    }

    /// calendar.create: create an event
    struct CalendarCreateArgs {
        let title: String
        let startInMin: Int
        let durationMin: Int
    }
    static func calendarCreate(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> CalendarCreateArgs? {
        guard f.count >= 3 else {
            host.argMissing(token, "calendar.create", 3, f.count); return nil
        }
        let title = f[0]
        guard let startInMin = Int(f[1]) else { host.argBad(token, "calendar.create", "startInMin", "int", f[1]); return nil }
        guard let durationMin = Int(f[2]) else { host.argBad(token, "calendar.create", "durationMin", "int", f[2]); return nil }
        return CalendarCreateArgs(title: title, startInMin: startInMin, durationMin: durationMin)
    }

    /// calendar.upcoming: events in the next N days
    struct CalendarUpcomingArgs {
        let days: Int
    }
    static func calendarUpcoming(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> CalendarUpcomingArgs? {
        guard f.count >= 1 else {
            host.argMissing(token, "calendar.upcoming", 1, f.count); return nil
        }
        guard let days = Int(f[0]) else { host.argBad(token, "calendar.upcoming", "days", "int", f[0]); return nil }
        return CalendarUpcomingArgs(days: days)
    }

    /// fs.write: write a file in the app's directory
    struct FsWriteArgs {
        let name: String
        let content: String
    }
    static func fsWrite(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> FsWriteArgs? {
        guard f.count >= 2 else {
            host.argMissing(token, "fs.write", 2, f.count); return nil
        }
        let name = f[0]
        let content = f[1]
        return FsWriteArgs(name: name, content: content)
    }

    /// haptics.vibrate: a single buzz, in milliseconds
    struct HapticsVibrateArgs {
        let ms: Int
    }
    static func hapticsVibrate(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> HapticsVibrateArgs? {
        guard f.count >= 1 else {
            host.argMissing(token, "haptics.vibrate", 1, f.count); return nil
        }
        guard let ms = Int(f[0]) else { host.argBad(token, "haptics.vibrate", "ms", "int", f[0]); return nil }
        return HapticsVibrateArgs(ms: ms)
    }

    /// location.watchBackground: the Android tracking notification
    struct LocationWatchBackgroundArgs {
        let title: String
        let body: String
    }
    static func locationWatchBackground(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> LocationWatchBackgroundArgs? {
        guard f.count >= 2 else {
            host.argMissing(token, "location.watchBackground", 2, f.count); return nil
        }
        let title = f[0]
        let body = f[1]
        return LocationWatchBackgroundArgs(title: title, body: body)
    }

    /// notif.notify: post a local notification
    struct NotifNotifyArgs {
        let title: String
        let body: String
    }
    static func notifNotify(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> NotifNotifyArgs? {
        guard f.count >= 2 else {
            host.argMissing(token, "notif.notify", 2, f.count); return nil
        }
        let title = f[0]
        let body = f[1]
        return NotifNotifyArgs(title: title, body: body)
    }

    /// pedometer.query: step history over a past window
    struct PedometerQueryArgs {
        let secondsAgo: Int
    }
    static func pedometerQuery(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> PedometerQueryArgs? {
        guard f.count >= 1 else {
            host.argMissing(token, "pedometer.query", 1, f.count); return nil
        }
        guard let secondsAgo = Int(f[0]) else { host.argBad(token, "pedometer.query", "secondsAgo", "int", f[0]); return nil }
        return PedometerQueryArgs(secondsAgo: secondsAgo)
    }

    /// secure.set: store a secret in the OS keystore
    struct SecureSetArgs {
        let key: String
        let value: String
    }
    static func secureSet(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> SecureSetArgs? {
        guard f.count >= 2 else {
            host.argMissing(token, "secure.set", 2, f.count); return nil
        }
        let key = f[0]
        let value = f[1]
        return SecureSetArgs(key: key, value: value)
    }

    /// torch.set: flashlight on or off
    struct TorchSetArgs {
        let on: Bool
    }
    static func torchSet(_ f: [String], _ token: String, _ host: ChuksArgFailer) -> TorchSetArgs? {
        guard f.count >= 1 else {
            host.argMissing(token, "torch.set", 1, f.count); return nil
        }
        let on = (f[0] == "1")
        return TorchSetArgs(on: on)
    }

}
