#!/usr/bin/env bash
# Autolinking for iOS, shared by every build path.
#
# A package declares its Swift in its own chuks.json (see appconfig.chuks); the sources
# compile into the app beside the host, and a generated registry hands them the commands
# whose namespace they claim. This is the whole of "autolinking" here, because the build
# calls swiftc directly: there is no CocoaPods or Xcode project to teach.
#
# This lives in its own file because it has to happen on the DEV path too. It used to sit
# inline in build.sh, which meant `chuks dev:ios` compiled the host alone and any app with
# a native package failed with "cannot find type 'ChuksModuleHost'". An app that installs
# one package was silently locked out of hot reload altogether, which is the single worst
# thing that can be true about a dev loop.
#
# Callers must have SDKROOT, PROJDIR and OUT set. Sets PKG_SRC and writes
# $OUT/ChuksPackageModules.swift.

chuks_ios_native_packages() {
    PKG_SRC="$(chuks run "$SDKROOT/appconfig.chuks" "$PROJDIR" mobile-sources ios 2>/dev/null | tr '\n' ' ')"
    {
        echo "// GENERATED by ios/native-packages.sh. Every installed package that ships a"
        echo "// native capability for iOS, so the registry can route commands to it. An app"
        echo "// with no such package gets an empty list and pays nothing."
        echo "func chuksPackageModules() -> [ChuksNativeModule.Type] { ["
        chuks run "$SDKROOT/appconfig.chuks" "$PROJDIR" mobile-modules ios 2>/dev/null |
            while IFS="$(printf '\t')" read -r ns cls; do [ -n "$cls" ] && echo "    $cls.self,"; done
        echo "] }"
        echo "// The view kinds those packages supply, if any."
        echo "func chuksPackageViews() -> [ChuksNativeView.Type] { ["
        chuks run "$SDKROOT/appconfig.chuks" "$PROJDIR" mobile-views ios 2>/dev/null |
            while IFS="$(printf '\t')" read -r kind cls; do [ -n "$cls" ] && echo "    $cls.self,"; done
        echo "] }"
    } > "$OUT/ChuksPackageModules.swift"
    [ -n "$PKG_SRC" ] && echo "   native packages: $(echo $PKG_SRC | wc -w | tr -d ' ') source file(s)"
    return 0
}

# A capability is one thing with two implementations, so the build says when the two
# disagree. Covers the framework's own hosts as well as every installed package. An
# undeclared gap is loud: it means a capability that is shipped and documented but dead on
# one platform, whose only other symptom is a callback that never fires. A difference the
# package DECLARED is counted, not listed.
chuks_capability_check() {
    local sym gaps notes
    sym="$(chuks run "$SDKROOT/appconfig.chuks" "$PROJDIR" mobile-symmetry "$SDKROOT" 2>/dev/null)"
    [ -n "$sym" ] || return 0
    gaps="$(printf '%s\n' "$sym" | grep -c '^gap' || true)"
    notes="$(printf '%s\n' "$sym" | grep -c '^note' || true)"
    if [ "$gaps" -gt 0 ]; then
        echo "   capability check: $gaps problem(s)"
        printf '%s\n' "$sym" | awk -F'\t' '$1=="gap" { printf "      %s  %s\n", $3, $4 }'
        echo "      Nothing answers a name like these, and nothing will say so at runtime: a command"
        echo "      reaches no capability, a view kind renders an empty container. Implement it, fix"
        echo "      the spelling, or declare the difference: \"capabilities\" and \"views\" in a package's"
        echo "      chuks.json, \"coreCapabilities\" in the SDK's."
    fi
    [ "$notes" -gt 0 ] && echo "   capability check: $notes declared platform difference(s)"
    return 0
}
